apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstash-config-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the storage capacity as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/iheb/Movie4U-Python-master/logstash-config/config"  # Update this with the path on your host machine
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstash-pipeline-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the storage capacity as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/iheb/Movie4U-Python-master/logstash-config/pipeline"  # Update this with the path on your host machine

