apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Match the storage capacity with the PersistentVolume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-pipeline-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Match the storage capacity with the PersistentVolume

