apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Match the storage capacity with the PersistentVolume

