apiVersion: v1
kind: PersistentVolume
metadata:
  name: kibana-config-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the storage capacity as needed
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/iheb/Movie4U-Python-master/kibana-config"  # Update this with the path on your host machine

