apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-code-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the storage capacity as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/iheb/Movie4U-Python-master/flask_app_code"  # Update this with the path on your host machine

